### ISSUE TITLE
out of bounds error

### ISSUE THREAD

**Issue by bjoern234** [flanglet/kanzi-go#5]
Hi,
I've tried to compress different datasets with different levels and often got out of bounds errors, e.g.

`runtime error: index out of range [104857594] with length 104857592 (code 13)`
or 
`runtime error: index out of range [3] with length 3 (code 13)`

I've tested with releases 2.0 and 2.1
Is this a bug or are there any configurations to avoid this errors?

Thanks
Bjoern

**Comment by flanglet** [comment]
Thanks for the info.
Using the head source in master, I saw the first issue (using -l 8 or -l 9) and pushed a fix (commit 0bba60).
I did not see the other issue with -l 4. It works for me with this file.  Does this one happen with release 2.1 or 2.0 ?

**Comment by flanglet** [comment]
The other issue is in FSDCodec.go and has already been fixed in master (d0914e1) which is why I did not see it.

Minimal patch:
L121-145
        // Check several step values on a sub-block (no memory allocation)
        // Sample 2 sub-blocks
        in1 := src[1*count5-8 : 1*count5+count10-8]
        in2 := src[3*count5-8 : 3*count5+count10-8]

        for i := 8; i < count10; i++ {
                b1 := in1[i]
                histo[0][b1]++
                histo[1][b1^in1[i-1]]++
                histo[2][b1^in1[i-2]]++
                histo[3][b1^in1[i-3]]++
                histo[4][b1^in1[i-4]]++
                histo[5][b1^in1[i-8]]++
                b2 := in2[i]
                histo[0][b2]++
                histo[1][b2^in2[i-1]]++
                histo[2][b2^in2[i-2]]++
                histo[3][b2^in2[i-3]]++
                histo[4][b2^in2[i-4]]++
                histo[5][b2^in2[i-8]]++
        }
